### PR TITLE
Typescript & Version 1.0

### PR DESCRIPTION
**Pull request by jozanza**
Checklist:
- [x] `p8 init`
- [x] `p8 add`
- [x] `p8 install`
- [x] `p8 build`
- [x] `p8 run`
- [x] build standalone executables for download

### CODE REVIEW

**Comment by senf666** [comment]
looks good to merge

**Comment by jozanza** [comment]
@DannyCork Wow yeah I remember I spent a whirlwind weekend doing all this last year...and then I got busy apparently. 😅

I'll spend some time reviewing this again this weekend! Let me know if you want to help out with testing or whatever. I haven't used PICO-8 in a while, but hopefully this all still works.

**Comment by senf666** [comment]
yip would be happy to test this.

**Comment by jozanza** [comment]
@DannyCork this is out now. I probably won't have a ton of time to maintain this moving forwards, but feel free to file issues if you run into any or make PRs if you want to fix or add something. Cheers 🎉

**Pull request merged**
